service: secondchance

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
    include:
      - SUPABASE_URL
      - SUPABASE_ANON_KEY
      - JWT_SECRET
      - FRONTEND_URL
  serverless-offline:
    cacheInvalidation: true
    noPrependStageInUrl: true
    httpPort: 5001
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY}
    JWT_SECRET: ${env:JWT_SECRET}
    FRONTEND_URL: ${env:FRONTEND_URL}

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /api/{proxy+}
          method: ANY
          cors: true

  # Add other routes as needed 