service: secondchance

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5001
    host: localhost
    websocket: true
    noPrependStageInUrl: true
    corsConfig:
      origin: '*'
      headers:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      credentials: true

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /api/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /api/auth/login
          method: POST
          cors: true
      - http:
          path: /api/auth/register
          method: POST
          cors: true
      - http:
          path: /api/users/profile
          method: GET
          cors: true
      - http:
          path: /api/users/items
          method: GET
          cors: true
      - http:
          path: /api/users/purchases
          method: GET
          cors: true
      - http:
          path: /api/items
          method: GET
          cors: true
      - http:
          path: /api/items/{id}
          method: GET
          cors: true
      - http:
          path: /api/items
          method: POST
          cors: true
      - http:
          path: /api/items/{id}/purchase
          method: POST
          cors: true
      - http:
          path: /api/users/profile
          method: PUT
          cors: true
      # Add other routes as needed 